### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by GuiAGSevero** [yzPeedro/SugoiAPI#3]
A Api está retornando 503 Service Unavailable

**Comment by yzPeedro** [comment]
A api está desativada à alguns meses por falta de hospedagem e a instabilidade nos provedores dos animes, esperamos retornar algum dia :(

**Comment by KingDasWinx** [comment]
Eu estava fazendo uma api de scrapping usando nodejs com as ferramentas pupperteer e express. Estou usando o site mangaschan.net para o scrapping. Está 70% concluida, talvez eu poste ela quando terminar.

**Comment by yzPeedro** [comment]
agradeço o suporte, acabei voltando o projeto à ativa, infelizmente ainda não tenho uma hospedagem confiável para compartilhar a api publicamente, mas caso queira, já é possível consumir a API na versão 2.0.0 rodando localmente  🎉
