### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by heyliceeee** [yzPeedro/SugoiAPI#4]

**Comment by yzPeedro** [comment]
Opa, boa tarde @heyliceeee, tudo certo?
A api ficou bastante tempo parada pq eu não tive tempo de mexer nela e nesse meio tempo o heroku começou a ser um serviço de hospedagem que pede pra inserir o cartão pra utilizar, ou seja, a qualquer momento podem me cobrar pra manter o projeto na ativa, e como é algo que não monetizo (e nem vou), não fazia sentido manter o projeto hospedado na heroku, mas trago boas notícias!!!

Vi sua issue à alguns dias atrás e lembrei do projeto, consegui separar um tempo para trabalhar nele e de maneira mais tecnológica também (afinal se passaram dois anos desde à ultima atualização rs), hoje faço o release da versão 2.0.0, infelizmente ainda sem hospedagem, mas isso é um problema que pretendo resolver o mais rápido possível, de toda maneira, já é possível rodar o projeto localmente, conforme forem surgindo bugs vou mantendo atualizado com novas versões, agradeço sua issue que me fez voltar a trabalhar nesse projeto, contribuição não é só apenas com código, todo detalhe importa, valeu!!!
